repos:
  - repo: local
    hooks:
      - id: generate-version
        name: generate-version
        # We use a shell compound command to generate the file and then stage it
        entry: uv run python scripts/generate_version.py
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff-format
      # - id: ruff
      #   args: [ --fix, --exit-non-zero-on-fix ]

  # - repo: local
  #   hooks:
  #     - id: python-unittest
  #       name: python-unittest
  #       entry: uv run python -m unittest discover tests
  #       language: system
  #       pass_filenames: false
  #       always_run: true