services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pf_sync_app
    env_file: ./secrets/.env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - seq
    # The Gateway Router
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  worker_pf_jira:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: pf_sync_worker_pf_jira
    env_file: ./secrets/.env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - redis
      - seq
    # The Isolated Domain Worker
    command: arq src.domain.pf_jira.tasks.WorkerSettings
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: pf_sync_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: pf_sync_seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=InternalDev123!
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  seq_data: